// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Saba","status":true,"description":"","parameters":{}},
{"name":"KisekiWindow","status":true,"description":"画面下にアクターの情報を表示します","parameters":{"HideSwitchId":"2","ShowTp?":"false","AreaWidth":"130"}},
{"name":"Tachie","status":true,"description":"","parameters":{"useTextureAtlas":"true","actor1offset":"-50, 10","actor2offset":"0, 0","actor3offset":"0, 0","actor4offset":"0, 0","actor5offset":"0, 0","actor6offset":"0, 0","actor7offset":"0, 0","actor8offset":"0, 0","actor9offset":"0, 0","actor10offset":"0, 0"}},
{"name":"SimpleScenario","status":true,"description":"テキストファイルからツクールのイベントを書き出すプラグインです。","parameters":{"autoWordWrap":"true"}},
{"name":"YED_WordWrap","status":true,"description":"文章の改行機能を提供します。長文を適切な位置で改行します。","parameters":{"Break Word":"true"}},
{"name":"SimpleScenarioValidator","status":true,"description":"","parameters":{}}
];
