// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KisekiWindow","status":true,"description":"画面下にアクターの情報を表示します","parameters":{"HideSwitchId":"2","ShowTp?":"false","AreaWidth":"130"}},
{"name":"gal","status":true,"description":"","parameters":{}}
];
